#ifndef CAMERAQUALITY_H
#define CAMERAQUALITY_H

typedef enum {
    CAMERA_QUALITY_VERY_LOW = 1,
    CAMERA_QUALITY_LOW = 2,
    CAMERA_QUALITY_GOOD = 3,
    CAMERA_QUALITY_VERY_GOOD = 4,
    CAMERA_QUALITY_LIGH = 5,
    CAMERA_QUALITY_VERY_LIGH = 6,
    CAMERA_QUALITY_PERFECT = 7,
    CAMERA_QUALITY_MAX = 8,
}CameraQuality;

#endif 